// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmyamagofcykceqmujxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1teWFtYWdvZmN5a2NlcW11anhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDEyMjEsImV4cCI6MjA2NzIxNzIyMX0.uZ1GtrIuyIqBfT5D-QaPxyZE7FH4OCS1ubljZnY885c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});